### ISSUE TITLE
Unknown error message emitted on error event

### ISSUE THREAD

**Issue by itsmishra19** [NezuChan/nezu-gateway#125]
```js
service-gateway-1  | [2023-03-31 19:34:20.000 +0000] FATAL (nezu-gateway/7): Unhandled 'error' event emitted, received [object Object]
service-gateway-1  |     err: {
service-gateway-1  |       "type": "Error",
service-gateway-1  |       "message": "Unhandled 'error' event emitted, received [object Object]",
service-gateway-1  |       "stack":
service-gateway-1  |           Error: Unhandled 'error' event emitted, received [object Object]
service-gateway-1  |               at WebSocketManager.emit (file:///app/node_modules/@vladfrangu/async_event_emitter/dist/index.mjs:213:19)
service-gateway-1  |               at ChildProcess.<anonymous> (file:///app/dist/Utilities/Websocket/ProcessShardingStrategy.js:130:26)
service-gateway-1  |               at ChildProcess.emit (node:events:513:28)
service-gateway-1  |               at maybeClose (node:internal/child_process:1091:16)
service-gateway-1  |               at ChildProcess._handle.onexit (node:internal/child_process:302:5)
service-gateway-1  |       "context": {
service-gateway-1  |         "error": {},
service-gateway-1  |         "shardId": 48
service-gateway-1  |       }
service-gateway-1  |     }
``` 
this error was thrown multiple times

**Comment by KagChi** [comment]
very informative title

**Comment by itsmishra19** [comment]
> very informative title

Ic

**Comment by KagChi** [comment]
Fixed on https://github.com/NezuChan/nezu-gateway/commit/3f4bd1cd8cffd6a1199cfca469273f5e3b8b5949
